# Generated by Django 4.2.7 on 2024-01-31 09:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import filmnews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='film-news/images/filmnews.jpg', null=True, upload_to='film-news/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'bmp', 'webp', 'svg', 'heic', 'heif', 'tiff', 'tif', 'bmp', 'gif'], message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), filmnews.models.validate_file_size])),
                ('video', models.FileField(blank=True, null=True, upload_to='film-news/videos', validators=[django.core.validators.FileExtensionValidator(message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), filmnews.models.validate_video_size])),
                ('youtube', models.TextField(blank=True, max_length=300, null=True)),
                ('body', models.TextField(max_length=400)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
