# Generated by Django 4.2.7 on 2024-01-31 17:07

import django.core.validators
from django.db import migrations, models
import filmnews.models


class Migration(migrations.Migration):

    dependencies = [
        ('filmnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmnewsmodel',
            name='image',
            field=models.ImageField(blank=True, default='film-news/images/filmnews.jpg', help_text="Rasm va Video 16:9 formatda bo'lishi kerak", null=True, upload_to='film-news/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'bmp', 'webp', 'svg', 'heic', 'heif', 'tiff', 'tif', 'bmp', 'gif'], message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), filmnews.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filmnewsmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='film-news/videos', validators=[django.core.validators.FileExtensionValidator(message='iltimos faqat video yuklang va hajmi 12mb dan oshmasligi kerak'), filmnews.models.validate_video_size]),
        ),
    ]
