# Generated by Django 4.2.7 on 2024-01-31 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('title_addtext', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('poster', models.ImageField(upload_to='films/posters/')),
                ('poster_16_9', models.ImageField(blank=True, null=True, upload_to='films/posters_16_9')),
                ('teaser', models.FileField(blank=True, null=True, upload_to='videos/film_teasers/')),
                ('trailer', models.CharField(blank=True, help_text='Agar teaser kiritsangiz, trailer kiritish shart emas', max_length=500, null=True)),
                ('sifat360p', models.TextField(blank=True, help_text="Agar serial joylaseyz serial deb nomlangan inputlarni to'ldiring", max_length=1000, null=True)),
                ('sifat480p', models.TextField(blank=True, max_length=1000, null=True)),
                ('sifat720p', models.TextField(blank=True, max_length=1000, null=True)),
                ('sifat1080p', models.TextField(blank=True, max_length=1000, null=True)),
                ('sifat2K', models.TextField(blank=True, max_length=1000, null=True)),
                ('sifat4K', models.TextField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, max_length=3000, null=True)),
                ('actors', models.CharField(blank=True, max_length=1000, null=True)),
                ('director', models.CharField(blank=True, max_length=500, null=True)),
                ('yosh_chegarasi', models.SmallIntegerField(default=16, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('kinomakon_rating', models.FloatField(default=0.0, null=True)),
                ('imdb_rating', models.FloatField(default=0.0, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=500, null=True)),
                ('davomiy_soat', models.CharField(blank=True, max_length=4, null=True)),
                ('davomiy_minut', models.CharField(blank=True, max_length=3, null=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('full_title', models.CharField(blank=True, help_text='Hech narsa yozishingiz shart emas', max_length=200, null=True)),
                ('carouselda_korsat', models.BooleanField(blank=True, default=False, null=True)),
                ('tavsiya', models.BooleanField(blank=True, default=False, null=True)),
                ('film_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mualliflik', models.BooleanField(default=False, help_text="Film mualliflik huquqi buzilsa shu orqali o'chirib qo'yiladi...!")),
                ('active', models.BooleanField(default=True, help_text="vaqtinchalik o'chirib qo'yish....")),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.countrymodel')),
                ('country2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.countrymodel2')),
                ('country3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.countrymodel3')),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JanrModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KinoOlamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1940), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
        migrations.CreateModel(
            name='SerialParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=333)),
                ('filmqism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialqism', to='film.filmmodel')),
            ],
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='film.janrmodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.janrmodel2'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.janrmodel3'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.janrmodel4'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.janrmodel5'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='janr_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.janrmodel6'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='kinoolam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.kinoolammodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.languagemodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='language_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.languagemodel2'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.typemodel'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.yearmodel'),
        ),
        migrations.CreateModel(
            name='FilmLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, null=True)),
                ('saved', models.BooleanField(default=False)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='film.filmmodel')),
            ],
        ),
    ]
