# Generated by Django 4.2.7 on 2024-01-31 10:01

import django.core.validators
from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_remove_filmlike_saved_alter_filmmodel_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=models.ImageField(upload_to='films/posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'bmp', 'webp', 'svg', 'heic', 'heif', 'tiff', 'tif', 'bmp', 'gif'], message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), film.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='poster_16_9',
            field=models.ImageField(blank=True, null=True, upload_to='films/posters_16_9', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'bmp', 'webp', 'svg', 'heic', 'heif', 'tiff', 'tif', 'bmp', 'gif'], message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), film.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='teaser',
            field=models.FileField(blank=True, null=True, upload_to='videos/film_teasers/', validators=[film.models.validate_video_size]),
        ),
    ]
