# Generated by Django 4.2.7 on 2024-01-31 11:26

import django.core.validators
from django.db import migrations, models
import film.models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_alter_filmmodel_poster_alter_filmmodel_poster_16_9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=models.ImageField(help_text="To'ldirish majburiy va Rasm hajmi 0.7mb dan baland bo'lmasligi shart!", upload_to='films/posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'bmp', 'webp', 'svg', 'heic', 'heif', 'tiff', 'tif', 'bmp', 'gif'], message='iltimos faqat rasm yuklang va hajmi 0.7mb dan oshmasligi kerak'), film.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='poster_16_9',
            field=models.ImageField(blank=True, help_text="Rasm hajmi 0.7mb dan baland bo'lmasligi shart!", null=True, upload_to='films/posters_16_9', validators=[film.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='teaser',
            field=models.FileField(blank=True, help_text="Video hajmi 15 megabaytdan katta bo'lamsligi shart", null=True, upload_to='videos/film_teasers/', validators=[film.models.validate_video_size]),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='trailer',
            field=models.CharField(blank=True, help_text='YouTube html kod kiritiladi(notebook kerak) -- Agar teaser kiritsangiz, trailer kiritish shart emas', max_length=500, null=True),
        ),
    ]
