# Generated by Django 4.2.7 on 2024-01-31 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_filmmodel_poster_alter_filmmodel_poster_16_9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlike',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filmsaved',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
